<?php

use Illuminate\Database\Seeder;

class MenusTableSeeder extends Seeder {

	/**
	 * Auto generated seed file
	 *
	 * @return void
	 */
	public function run()
	{
		\DB::table('menus')->delete();

		\DB::table('menus')->insert(array (
			0 =>
			array (
				'id' => '4',
				'title' => 'Home',
				'alias' => 'public-top-menu-home',
				'link' => '/',
				'icon' => '',
				'link_manual' => '',
				'category' => '0',
				'position' => '1',
				'display_text' => 'Welcome to Doptor CMS.',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '1',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			1 =>
			array (
				'id' => '5',
				'title' => 'About Us',
				'alias' => 'public-top-menu-about-us',
				'link' => 'pages/about-us',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '0',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '3',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			2 =>
			array (
				'id' => '6',
				'title' => 'Backend',
				'alias' => 'public-small-menu-right-backend',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => 'backend',
				'category' => '0',
				'position' => '4',
				'display_text' => '',
				'same_window' => '0',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '1',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			3 =>
			array (
				'id' => '7',
				'title' => 'Admin',
				'alias' => 'public-small-menu-right-admin',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => 'admin',
				'category' => '0',
				'position' => '4',
				'display_text' => '',
				'same_window' => '0',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '2',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			4 =>
			array (
				'id' => '8',
				'title' => 'About Us',
				'alias' => 'public-bottom-menu-about-us',
				'link' => 'pages/about-us',
				'icon' => '',
				'link_manual' => '',
				'category' => '0',
				'position' => '2',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '0',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			5 =>
			array (
				'id' => '9',
				'title' => 'Demo',
				'alias' => 'public-small-menu-left-demo',
				'link' => 'pages/demo',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '3',
				'display_text' => '',
				'same_window' => '0',
				'show_image' => '0',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '1',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			6 =>
			array (
				'id' => '10',
				'title' => 'Download',
				'alias' => 'public-small-menu-left-download',
				'link' => 'pages/under-construction',
				'icon' => '',
				'link_manual' => '',
				'category' => '0',
				'position' => '3',
				'display_text' => '',
				'same_window' => '0',
				'show_image' => '0',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '2',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			7 =>
			array (
				'id' => '13',
				'title' => 'Contact Us',
				'alias' => 'public-top-menu-contact-us',
				'link' => 'link_type/modules/form23',
				'icon' => '',
				'link_manual' => '',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'unpublished',
				'parent' => '0',
				'order' => '8',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			8 =>
			array (
				'id' => '14',
				'title' => 'Main',
				'alias' => 'public-top-menu-main',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '2',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			9 =>
			array (
				'id' => '15',
				'title' => 'Sub-1',
				'alias' => 'public-top-menu-sub-1',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '14',
				'order' => '0',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			10 =>
			array (
				'id' => '16',
				'title' => 'Sub-2',
				'alias' => 'public-top-menu-sub-2',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '14',
				'order' => '0',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			11 =>
			array (
				'id' => '17',
				'title' => 'Sub-3',
				'alias' => 'public-top-menu-sub-3',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '14',
				'order' => '0',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			12 =>
			array (
				'id' => '18',
				'title' => 'Sub-Sub-1',
				'alias' => 'public-top-menu-sub-sub-1',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '15',
				'order' => '0',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			13 =>
			array (
				'id' => '19',
				'title' => 'Sub-Sub-2',
				'alias' => 'public-top-menu-sub-sub-2',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '15',
				'order' => '0',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			14 =>
			array (
				'id' => '20',
				'title' => 'Sub-Sub-Sub-1',
				'alias' => 'public-top-menu-sub-sub-sub-1',
				'link' => 'manual',
				'icon' => '',
				'link_manual' => '#',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '1',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '18',
				'order' => '0',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => '',
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
			15 =>
			array (
				'id' => '32',
				'title' => 'Help',
				'alias' => 'public-top-menu-help',
				'link' => 'pages/help',
				'icon' => NULL,
				'link_manual' => '',
				'category' => '0',
				'position' => '1',
				'display_text' => '',
				'same_window' => '1',
				'show_image' => '0',
				'is_wrapper' => '0',
				'wrapper_width' => NULL,
				'wrapper_height' => NULL,
				'status' => 'published',
				'parent' => '0',
				'order' => '10',
				'target' => 'public',
				'publish_start' => NULL,
				'publish_end' => NULL,
				'meta_title' => NULL,
				'meta_description' => '',
				'meta_keywords' => '',
				'created_at' => date('Y-m-d h:i:s', time()),
				'updated_at' => date('Y-m-d h:i:s', time()),
			),
		));
	}

}
