<?php namespace Modules\Doptor\CompanyInfo\Database\Seeds;

use Illuminate\Database\Seeder;

use Modules\Doptor\CompanyInfo\Models\Country;

class CountriesTableSeeder extends Seeder
{
    public function run()
    {
        $countries = [];
        $countries[] = ["code"=>"AF", "name"=>"Afghanistan", "dialing_code"=>"+93"];
        $countries[] = ["code"=>"AL", "name"=>"Albania", "dialing_code"=>"+355"];
        $countries[] = ["code"=>"DZ", "name"=>"Algeria", "dialing_code"=>"+213"];
        $countries[] = ["code"=>"AS", "name"=>"American Samoa", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"AD", "name"=>"Andorra", "dialing_code"=>"+376"];
        $countries[] = ["code"=>"AO", "name"=>"Angola", "dialing_code"=>"+244"];
        $countries[] = ["code"=>"AI", "name"=>"Anguilla", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"AG", "name"=>"Antigua", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"AR", "name"=>"Argentina", "dialing_code"=>"+54"];
        $countries[] = ["code"=>"AM", "name"=>"Armenia", "dialing_code"=>"+374"];
        $countries[] = ["code"=>"AW", "name"=>"Aruba", "dialing_code"=>"+297"];
        $countries[] = ["code"=>"AU", "name"=>"Australia", "dialing_code"=>"+61"];
        $countries[] = ["code"=>"AT", "name"=>"Austria", "dialing_code"=>"+43"];
        $countries[] = ["code"=>"AZ", "name"=>"Azerbaijan", "dialing_code"=>"+994"];
        $countries[] = ["code"=>"BH", "name"=>"Bahrain", "dialing_code"=>"+973"];
        $countries[] = ["code"=>"BD", "name"=>"Bangladesh", "dialing_code"=>"+880"];
        $countries[] = ["code"=>"BB", "name"=>"Barbados", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"BY", "name"=>"Belarus", "dialing_code"=>"+375"];
        $countries[] = ["code"=>"BE", "name"=>"Belgium", "dialing_code"=>"+32"];
        $countries[] = ["code"=>"BZ", "name"=>"Belize", "dialing_code"=>"+501"];
        $countries[] = ["code"=>"BJ", "name"=>"Benin", "dialing_code"=>"+229"];
        $countries[] = ["code"=>"BM", "name"=>"Bermuda", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"BT", "name"=>"Bhutan", "dialing_code"=>"+975"];
        $countries[] = ["code"=>"BO", "name"=>"Bolivia", "dialing_code"=>"+591"];
        $countries[] = ["code"=>"BA", "name"=>"Bosnia and Herzegovina", "dialing_code"=>"+387"];
        $countries[] = ["code"=>"BW", "name"=>"Botswana", "dialing_code"=>"+267"];
        $countries[] = ["code"=>"BR", "name"=>"Brazil", "dialing_code"=>"+55"];
        $countries[] = ["code"=>"IO", "name"=>"British Indian Ocean Territory", "dialing_code"=>"+246"];
        $countries[] = ["code"=>"VG", "name"=>"British Virgin Islands", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"BN", "name"=>"Brunei", "dialing_code"=>"+673"];
        $countries[] = ["code"=>"BG", "name"=>"Bulgaria", "dialing_code"=>"+359"];
        $countries[] = ["code"=>"BF", "name"=>"Burkina Faso", "dialing_code"=>"+226"];
        $countries[] = ["code"=>"MM", "name"=>"Burma Myanmar" , "dialing_code"=>"+95"];
        $countries[] = ["code"=>"BI", "name"=>"Burundi", "dialing_code"=>"+257"];
        $countries[] = ["code"=>"KH", "name"=>"Cambodia", "dialing_code"=>"+855"];
        $countries[] = ["code"=>"CM", "name"=>"Cameroon", "dialing_code"=>"+237"];
        $countries[] = ["code"=>"CA", "name"=>"Canada", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"CV", "name"=>"Cape Verde", "dialing_code"=>"+238"];
        $countries[] = ["code"=>"KY", "name"=>"Cayman Islands", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"CF", "name"=>"Central African Republic", "dialing_code"=>"+236"];
        $countries[] = ["code"=>"TD", "name"=>"Chad", "dialing_code"=>"+235"];
        $countries[] = ["code"=>"CL", "name"=>"Chile", "dialing_code"=>"+56"];
        $countries[] = ["code"=>"CN", "name"=>"China", "dialing_code"=>"+86"];
        $countries[] = ["code"=>"CO", "name"=>"Colombia", "dialing_code"=>"+57"];
        $countries[] = ["code"=>"KM", "name"=>"Comoros", "dialing_code"=>"+269"];
        $countries[] = ["code"=>"CK", "name"=>"Cook Islands", "dialing_code"=>"+682"];
        $countries[] = ["code"=>"CR", "name"=>"Costa Rica", "dialing_code"=>"+506"];
        $countries[] = ["code"=>"CI", "name"=>"Côte d'Ivoire" , "dialing_code"=>"+225"];
        $countries[] = ["code"=>"HR", "name"=>"Croatia", "dialing_code"=>"+385"];
        $countries[] = ["code"=>"CU", "name"=>"Cuba", "dialing_code"=>"+53"];
        $countries[] = ["code"=>"CY", "name"=>"Cyprus", "dialing_code"=>"+357"];
        $countries[] = ["code"=>"CZ", "name"=>"Czech Republic", "dialing_code"=>"+420"];
        $countries[] = ["code"=>"CD", "name"=>"Democratic Republic of Congo", "dialing_code"=>"+243"];
        $countries[] = ["code"=>"DK", "name"=>"Denmark", "dialing_code"=>"+45"];
        $countries[] = ["code"=>"DJ", "name"=>"Djibouti", "dialing_code"=>"+253"];
        $countries[] = ["code"=>"DM", "name"=>"Dominica", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"DO", "name"=>"Dominican Republic", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"EC", "name"=>"Ecuador", "dialing_code"=>"+593"];
        $countries[] = ["code"=>"EG", "name"=>"Egypt", "dialing_code"=>"+20"];
        $countries[] = ["code"=>"SV", "name"=>"El Salvador", "dialing_code"=>"+503"];
        $countries[] = ["code"=>"GQ", "name"=>"Equatorial Guinea", "dialing_code"=>"+240"];
        $countries[] = ["code"=>"ER", "name"=>"Eritrea", "dialing_code"=>"+291"];
        $countries[] = ["code"=>"EE", "name"=>"Estonia", "dialing_code"=>"+372"];
        $countries[] = ["code"=>"ET", "name"=>"Ethiopia", "dialing_code"=>"+251"];
        $countries[] = ["code"=>"FK", "name"=>"Falkland Islands", "dialing_code"=>"+500"];
        $countries[] = ["code"=>"FO", "name"=>"Faroe Islands", "dialing_code"=>"+298"];
        $countries[] = ["code"=>"FM", "name"=>"Federated States of Micronesia", "dialing_code"=>"+691"];
        $countries[] = ["code"=>"FJ", "name"=>"Fiji", "dialing_code"=>"+679"];
        $countries[] = ["code"=>"FI", "name"=>"Finland", "dialing_code"=>"+358"];
        $countries[] = ["code"=>"FR", "name"=>"France", "dialing_code"=>"+33"];
        $countries[] = ["code"=>"GF", "name"=>"French Guiana", "dialing_code"=>"+594"];
        $countries[] = ["code"=>"PF", "name"=>"French Polynesia", "dialing_code"=>"+689"];
        $countries[] = ["code"=>"GA", "name"=>"Gabon", "dialing_code"=>"+241"];
        $countries[] = ["code"=>"GE", "name"=>"Georgia", "dialing_code"=>"+995"];
        $countries[] = ["code"=>"DE", "name"=>"Germany", "dialing_code"=>"+49"];
        $countries[] = ["code"=>"GH", "name"=>"Ghana", "dialing_code"=>"+233"];
        $countries[] = ["code"=>"GI", "name"=>"Gibraltar", "dialing_code"=>"+350"];
        $countries[] = ["code"=>"GR", "name"=>"Greece", "dialing_code"=>"+30"];
        $countries[] = ["code"=>"GL", "name"=>"Greenland", "dialing_code"=>"+299"];
        $countries[] = ["code"=>"GD", "name"=>"Grenada", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"GP", "name"=>"Guadeloupe", "dialing_code"=>"+590"];
        $countries[] = ["code"=>"GU", "name"=>"Guam", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"GT", "name"=>"Guatemala", "dialing_code"=>"+502"];
        $countries[] = ["code"=>"GN", "name"=>"Guinea", "dialing_code"=>"+224"];
        $countries[] = ["code"=>"GW", "name"=>"Guinea-Bissau", "dialing_code"=>"+245"];
        $countries[] = ["code"=>"GY", "name"=>"Guyana", "dialing_code"=>"+592"];
        $countries[] = ["code"=>"HT", "name"=>"Haiti", "dialing_code"=>"+509"];
        $countries[] = ["code"=>"HN", "name"=>"Honduras", "dialing_code"=>"+504"];
        $countries[] = ["code"=>"HK", "name"=>"Hong Kong", "dialing_code"=>"+852"];
        $countries[] = ["code"=>"HU", "name"=>"Hungary", "dialing_code"=>"+36"];
        $countries[] = ["code"=>"IS", "name"=>"Iceland", "dialing_code"=>"+354"];
        $countries[] = ["code"=>"IN", "name"=>"India", "dialing_code"=>"+91"];
        $countries[] = ["code"=>"ID", "name"=>"Indonesia", "dialing_code"=>"+62"];
        $countries[] = ["code"=>"IR", "name"=>"Iran", "dialing_code"=>"+98"];
        $countries[] = ["code"=>"IQ", "name"=>"Iraq", "dialing_code"=>"+964"];
        $countries[] = ["code"=>"IE", "name"=>"Ireland", "dialing_code"=>"+353"];
        $countries[] = ["code"=>"IL", "name"=>"Israel", "dialing_code"=>"+972"];
        $countries[] = ["code"=>"IT", "name"=>"Italy", "dialing_code"=>"+39"];
        $countries[] = ["code"=>"JM", "name"=>"Jamaica", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"JP", "name"=>"Japan", "dialing_code"=>"+81"];
        $countries[] = ["code"=>"JO", "name"=>"Jordan", "dialing_code"=>"+962"];
        $countries[] = ["code"=>"KZ", "name"=>"Kazakhstan", "dialing_code"=>"+7"];
        $countries[] = ["code"=>"KE", "name"=>"Kenya", "dialing_code"=>"+254"];
        $countries[] = ["code"=>"KI", "name"=>"Kiribati", "dialing_code"=>"+686"];
        $countries[] = ["code"=>"XK", "name"=>"Kosovo", "dialing_code"=>"+381"];
        $countries[] = ["code"=>"KW", "name"=>"Kuwait", "dialing_code"=>"+965"];
        $countries[] = ["code"=>"KG", "name"=>"Kyrgyzstan", "dialing_code"=>"+996"];
        $countries[] = ["code"=>"LA", "name"=>"Laos", "dialing_code"=>"+856"];
        $countries[] = ["code"=>"LV", "name"=>"Latvia", "dialing_code"=>"+371"];
        $countries[] = ["code"=>"LB", "name"=>"Lebanon", "dialing_code"=>"+961"];
        $countries[] = ["code"=>"LS", "name"=>"Lesotho", "dialing_code"=>"+266"];
        $countries[] = ["code"=>"LR", "name"=>"Liberia", "dialing_code"=>"+231"];
        $countries[] = ["code"=>"LY", "name"=>"Libya", "dialing_code"=>"+218"];
        $countries[] = ["code"=>"LI", "name"=>"Liechtenstein", "dialing_code"=>"+423"];
        $countries[] = ["code"=>"LT", "name"=>"Lithuania", "dialing_code"=>"+370"];
        $countries[] = ["code"=>"LU", "name"=>"Luxembourg", "dialing_code"=>"+352"];
        $countries[] = ["code"=>"MO", "name"=>"Macau", "dialing_code"=>"+853"];
        $countries[] = ["code"=>"MK", "name"=>"Macedonia", "dialing_code"=>"+389"];
        $countries[] = ["code"=>"MG", "name"=>"Madagascar", "dialing_code"=>"+261"];
        $countries[] = ["code"=>"MW", "name"=>"Malawi", "dialing_code"=>"+265"];
        $countries[] = ["code"=>"MY", "name"=>"Malaysia", "dialing_code"=>"+60"];
        $countries[] = ["code"=>"MV", "name"=>"Maldives", "dialing_code"=>"+960"];
        $countries[] = ["code"=>"ML", "name"=>"Mali", "dialing_code"=>"+223"];
        $countries[] = ["code"=>"MT", "name"=>"Malta", "dialing_code"=>"+356"];
        $countries[] = ["code"=>"MH", "name"=>"Marshall Islands", "dialing_code"=>"+692"];
        $countries[] = ["code"=>"MQ", "name"=>"Martinique", "dialing_code"=>"+596"];
        $countries[] = ["code"=>"MR", "name"=>"Mauritania", "dialing_code"=>"+222"];
        $countries[] = ["code"=>"MU", "name"=>"Mauritius", "dialing_code"=>"+230"];
        $countries[] = ["code"=>"YT", "name"=>"Mayotte", "dialing_code"=>"+262"];
        $countries[] = ["code"=>"MX", "name"=>"Mexico", "dialing_code"=>"+52"];
        $countries[] = ["code"=>"MD", "name"=>"Moldova", "dialing_code"=>"+373"];
        $countries[] = ["code"=>"MC", "name"=>"Monaco", "dialing_code"=>"+377"];
        $countries[] = ["code"=>"MN", "name"=>"Mongolia", "dialing_code"=>"+976"];
        $countries[] = ["code"=>"ME", "name"=>"Montenegro", "dialing_code"=>"+382"];
        $countries[] = ["code"=>"MS", "name"=>"Montserrat", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"MA", "name"=>"Morocco", "dialing_code"=>"+212"];
        $countries[] = ["code"=>"MZ", "name"=>"Mozambique", "dialing_code"=>"+258"];
        $countries[] = ["code"=>"NA", "name"=>"Namibia", "dialing_code"=>"+264"];
        $countries[] = ["code"=>"NR", "name"=>"Nauru", "dialing_code"=>"+674"];
        $countries[] = ["code"=>"NP", "name"=>"Nepal", "dialing_code"=>"+977"];
        $countries[] = ["code"=>"NL", "name"=>"Netherlands", "dialing_code"=>"+31"];
        $countries[] = ["code"=>"AN", "name"=>"Netherlands Antilles", "dialing_code"=>"+599"];
        $countries[] = ["code"=>"NC", "name"=>"New Caledonia", "dialing_code"=>"+687"];
        $countries[] = ["code"=>"NZ", "name"=>"New Zealand", "dialing_code"=>"+64"];
        $countries[] = ["code"=>"NI", "name"=>"Nicaragua", "dialing_code"=>"+505"];
        $countries[] = ["code"=>"NE", "name"=>"Niger", "dialing_code"=>"+227"];
        $countries[] = ["code"=>"NG", "name"=>"Nigeria", "dialing_code"=>"+234"];
        $countries[] = ["code"=>"NU", "name"=>"Niue", "dialing_code"=>"+683"];
        $countries[] = ["code"=>"NF", "name"=>"Norfolk Island", "dialing_code"=>"+672"];
        $countries[] = ["code"=>"KP", "name"=>"North Korea", "dialing_code"=>"+850"];
        $countries[] = ["code"=>"MP", "name"=>"Northern Mariana Islands", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"NO", "name"=>"Norway", "dialing_code"=>"+47"];
        $countries[] = ["code"=>"OM", "name"=>"Oman", "dialing_code"=>"+968"];
        $countries[] = ["code"=>"PK", "name"=>"Pakistan", "dialing_code"=>"+92"];
        $countries[] = ["code"=>"PW", "name"=>"Palau", "dialing_code"=>"+680"];
        $countries[] = ["code"=>"PS", "name"=>"Palestine", "dialing_code"=>"+970"];
        $countries[] = ["code"=>"PA", "name"=>"Panama", "dialing_code"=>"+507"];
        $countries[] = ["code"=>"PG", "name"=>"Papua New Guinea", "dialing_code"=>"+675"];
        $countries[] = ["code"=>"PY", "name"=>"Paraguay", "dialing_code"=>"+595"];
        $countries[] = ["code"=>"PE", "name"=>"Peru", "dialing_code"=>"+51"];
        $countries[] = ["code"=>"PH", "name"=>"Philippines", "dialing_code"=>"+63"];
        $countries[] = ["code"=>"PL", "name"=>"Poland", "dialing_code"=>"+48"];
        $countries[] = ["code"=>"PT", "name"=>"Portugal", "dialing_code"=>"+351"];
        $countries[] = ["code"=>"PR", "name"=>"Puerto Rico", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"QA", "name"=>"Qatar", "dialing_code"=>"+974"];
        $countries[] = ["code"=>"CG", "name"=>"Republic of the Congo", "dialing_code"=>"+242"];
        $countries[] = ["code"=>"RE", "name"=>"Réunion" , "dialing_code"=>"+262"];
        $countries[] = ["code"=>"RO", "name"=>"Romania", "dialing_code"=>"+40"];
        $countries[] = ["code"=>"RU", "name"=>"Russia", "dialing_code"=>"+7"];
        $countries[] = ["code"=>"RW", "name"=>"Rwanda", "dialing_code"=>"+250"];
        $countries[] = ["code"=>"BL", "name"=>"Saint Barthélemy" , "dialing_code"=>"+590"];
        $countries[] = ["code"=>"SH", "name"=>"Saint Helena", "dialing_code"=>"+290"];
        $countries[] = ["code"=>"KN", "name"=>"Saint Kitts and Nevis", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"MF", "name"=>"Saint Martin", "dialing_code"=>"+590"];
        $countries[] = ["code"=>"PM", "name"=>"Saint Pierre and Miquelon", "dialing_code"=>"+508"];
        $countries[] = ["code"=>"VC", "name"=>"Saint Vincent and the Grenadines", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"WS", "name"=>"Samoa", "dialing_code"=>"+685"];
        $countries[] = ["code"=>"SM", "name"=>"San Marino", "dialing_code"=>"+378"];
        $countries[] = ["code"=>"ST", "name"=>"São Tomé and Príncipe" , "dialing_code"=>"+239"];
        $countries[] = ["code"=>"SA", "name"=>"Saudi Arabia", "dialing_code"=>"+966"];
        $countries[] = ["code"=>"SN", "name"=>"Senegal", "dialing_code"=>"+221"];
        $countries[] = ["code"=>"RS", "name"=>"Serbia", "dialing_code"=>"+381"];
        $countries[] = ["code"=>"SC", "name"=>"Seychelles", "dialing_code"=>"+248"];
        $countries[] = ["code"=>"SL", "name"=>"Sierra Leone", "dialing_code"=>"+232"];
        $countries[] = ["code"=>"SG", "name"=>"Singapore", "dialing_code"=>"+65"];
        $countries[] = ["code"=>"SK", "name"=>"Slovakia", "dialing_code"=>"+421"];
        $countries[] = ["code"=>"SI", "name"=>"Slovenia", "dialing_code"=>"+386"];
        $countries[] = ["code"=>"SB", "name"=>"Solomon Islands", "dialing_code"=>"+677"];
        $countries[] = ["code"=>"SO", "name"=>"Somalia", "dialing_code"=>"+252"];
        $countries[] = ["code"=>"ZA", "name"=>"South Africa", "dialing_code"=>"+27"];
        $countries[] = ["code"=>"KR", "name"=>"South Korea", "dialing_code"=>"+82"];
        $countries[] = ["code"=>"ES", "name"=>"Spain", "dialing_code"=>"+34"];
        $countries[] = ["code"=>"LK", "name"=>"Sri Lanka", "dialing_code"=>"+94"];
        $countries[] = ["code"=>"LC", "name"=>"St. Lucia", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"SD", "name"=>"Sudan", "dialing_code"=>"+249"];
        $countries[] = ["code"=>"SR", "name"=>"Suriname", "dialing_code"=>"+597"];
        $countries[] = ["code"=>"SZ", "name"=>"Swaziland", "dialing_code"=>"+268"];
        $countries[] = ["code"=>"SE", "name"=>"Sweden", "dialing_code"=>"+46"];
        $countries[] = ["code"=>"CH", "name"=>"Switzerland", "dialing_code"=>"+41"];
        $countries[] = ["code"=>"SY", "name"=>"Syria", "dialing_code"=>"+963"];
        $countries[] = ["code"=>"TW", "name"=>"Taiwan", "dialing_code"=>"+886"];
        $countries[] = ["code"=>"TJ", "name"=>"Tajikistan", "dialing_code"=>"+992"];
        $countries[] = ["code"=>"TZ", "name"=>"Tanzania", "dialing_code"=>"+255"];
        $countries[] = ["code"=>"TH", "name"=>"Thailand", "dialing_code"=>"+66"];
        $countries[] = ["code"=>"BS", "name"=>"The Bahamas", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"GM", "name"=>"The Gambia", "dialing_code"=>"+220"];
        $countries[] = ["code"=>"TL", "name"=>"Timor-Leste", "dialing_code"=>"+670"];
        $countries[] = ["code"=>"TG", "name"=>"Togo", "dialing_code"=>"+228"];
        $countries[] = ["code"=>"TK", "name"=>"Tokelau", "dialing_code"=>"+690"];
        $countries[] = ["code"=>"TO", "name"=>"Tonga", "dialing_code"=>"+676"];
        $countries[] = ["code"=>"TT", "name"=>"Trinidad and Tobago", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"TN", "name"=>"Tunisia", "dialing_code"=>"+216"];
        $countries[] = ["code"=>"TR", "name"=>"Turkey", "dialing_code"=>"+90"];
        $countries[] = ["code"=>"TM", "name"=>"Turkmenistan", "dialing_code"=>"+993"];
        $countries[] = ["code"=>"TC", "name"=>"Turks and Caicos Islands", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"TV", "name"=>"Tuvalu", "dialing_code"=>"+688"];
        $countries[] = ["code"=>"UG", "name"=>"Uganda", "dialing_code"=>"+256"];
        $countries[] = ["code"=>"UA", "name"=>"Ukraine", "dialing_code"=>"+380"];
        $countries[] = ["code"=>"AE", "name"=>"United Arab Emirates", "dialing_code"=>"+971"];
        $countries[] = ["code"=>"GB", "name"=>"United Kingdom", "dialing_code"=>"+44"];
        $countries[] = ["code"=>"US", "name"=>"United States", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"UY", "name"=>"Uruguay", "dialing_code"=>"+598"];
        $countries[] = ["code"=>"VI", "name"=>"US Virgin Islands", "dialing_code"=>"+1"];
        $countries[] = ["code"=>"UZ", "name"=>"Uzbekistan", "dialing_code"=>"+998"];
        $countries[] = ["code"=>"VU", "name"=>"Vanuatu", "dialing_code"=>"+678"];
        $countries[] = ["code"=>"VA", "name"=>"Vatican City", "dialing_code"=>"+39"];
        $countries[] = ["code"=>"VE", "name"=>"Venezuela", "dialing_code"=>"+58"];
        $countries[] = ["code"=>"VN", "name"=>"Vietnam", "dialing_code"=>"+84"];
        $countries[] = ["code"=>"WF", "name"=>"Wallis and Futuna", "dialing_code"=>"+681"];
        $countries[] = ["code"=>"YE", "name"=>"Yemen", "dialing_code"=>"+967"];
        $countries[] = ["code"=>"ZM", "name"=>"Zambia", "dialing_code"=>"+260"];
        $countries[] = ["code"=>"ZW", "name"=>"Zimbabwe", "dialing_code"=>"+263"];

        Country::insert($countries);
    }
}
